---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12
  - certifi=2024.12.14
  - charset-normalizer=3.4.1
  - idna=3.10
  - numpy=2.2.2
  - pandas=2.2.3
  - pyarrow=19.0.0
  - python-dateutil=2.9.0.post0
  - pytz=2024.2
  - requests=2.32.3
  - six=1.17.0
  - tqdm=4.67.1
  - urllib3=2.3.0
